### ISSUE TITLE
Wowsers

### ISSUE THREAD

**Issue by njbotkin** [lachrist/aran#7]
That's a big refactoring you just pushed.  I'm sure you'll update the documentation, but I'm also very interested in understanding what you just did and why!

I'm very excited about Aran, it's the best-looking JS instrumentation tool I can find.

**Comment by lachrist** [comment]
I will be updating the documentation in the upcoming days.
Thanks for your interest!
After I published the new documentation I will happy to discuss remaining questions.

Kind Regards,
Laurent

On 2 Dec 2018, at 21:45, njbotkin <notifications@github.com<mailto:notifications@github.com>> wrote:


That's a big refactoring you just pushed. I'm sure you'll update the documentation, but I'm also very interested in understanding what you just did and why!

I'm very excited about aran, it's the best-looking JS instrumentation tool I can find.
