### ISSUE TITLE
Instrument code that does not require aran

### ISSUE THREAD

**Issue by retorquere** [lachrist/aran#9]
In the sample code, it is assumed that the instrumented code and the instrumenting code is ran in the same environment. I'm looking to instrument code as part of bundling, but the code generated by aran needs access to the `ADVICE` object, which doesn't exist in the generated code. Can I work around this and still use aran?

**Comment by lachrist** [comment]
Sorry for the extremely late answer. It is up to the user to make sure that the advice is available in the environment where the instrumented will be executed. It is possible to instrument the code in a separate process but you will have to bundle yourself the code that defines the advice with the instrumented code.
